import { generateClient } from "aws-amplify/api";
import { fetchAuthSession } from "aws-amplify/auth";

export const associateItemsWithApplication = async ({
  applicationId,
  items,
  associationType,
}: {
  applicationId: string;
  items: { id: string }[] | string[];
  associationType:
    | "Award"
    | "Education"
    | "SpecializedExperience"
    | "PastJob"
    | "Volunteer"
    | "Resume";
}) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }

  const client = generateClient();

  try {
    // Validate required parameters
    if (!applicationId || !items || items.length === 0) {
      throw new Error(
        `applicationId and non-empty ${associationType} items array are required`
      );
    }

    // Map to get the item IDs whether we received objects with IDs or just ID strings
    const itemIds = items.map((item) =>
      typeof item === "string" ? item : item.id
    );

    // Build the mutation name based on the associationType
    const mutationName = `create${associationType}Application`;

    // Build the input field name based on the associationType (lowercase first letter)
    const itemIdFieldName = `${
      associationType.charAt(0).toLowerCase() + associationType.slice(1)
    }Id`;

    // Create connections one at a time to avoid complex filter expressions
    const createdConnections = [];

    for (const itemId of itemIds) {
      const input = {
        [itemIdFieldName]: itemId,
        applicationId,
      };

      const response = await client.graphql({
        query: `
          mutation Create${associationType}Application($input: Create${associationType}ApplicationInput!) {
            ${mutationName}(input: $input) {
              id
              ${itemIdFieldName}
              applicationId
            }
          }
        `,
        variables: { input },
        authMode: "userPool",
      });

      if ("data" in response) {
        createdConnections.push(response.data[mutationName]);
      } else {
        throw new Error(
          `Unexpected response format from GraphQL operation for ${associationType}`
        );
      }
    }
    console.log(createdConnections);
    return createdConnections;
  } catch (error) {
    console.error(
      `Error associating ${associationType} with Application:`,
      error
    );
    throw error;
  }
};

export const createAndSaveApplication = async ({
  jobId,
  userId,
}: {
  jobId: string;
  userId: string;
}) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    // Redirect to login page
    return;
  }
  const client = generateClient();
  try {
    // Validate required parameters
    if (!jobId || !userId) {
      throw new Error("jobId and userId are required parameters");
    }

    // Create the Application input object
    const applicationInput = {
      jobId,
      userId,
      // Note: The ID will be auto-generated by Amplify
    };

    // Use the client.models approach in Amplify v2
    const response = await client.graphql({
      query: `
        mutation CreateApplication($input: CreateApplicationInput!) {
          createApplication(input: $input) {
            id
            jobId
            userId
            createdAt
            updatedAt
          }
        }
      `,
      variables: {
        input: applicationInput,
      },
      authMode: "userPool",
    });

    // Return the created Application
    if ("data" in response) {
      return response.data.createApplication;
    }
    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error creating Application:", error);
    throw error;
  }
};

export const getApplicationWithJob = async ({ id }: { id: string }) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }
  const client = generateClient();
  try {
    const response = await client.graphql({
      query: `
      query GetApplication($id: ID!) {
        getApplication(id: $id) {
        completedSteps
        id
        jobId
        userId
        job {
          id
            title
            department
            agencyDescription
            duties
            evaluationCriteria
            qualificationsSummary
            requiredDocuments
            usaJobsId
        }
        createdAt
        updatedAt
        }
      }
      `,
      variables: { id },
      authMode: "userPool",
    });

    if ("data" in response) {
      return response.data.getApplication;
    }
    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error fetching Application:", error);
    throw error;
  }
};

export const updateApplication = async ({
  id,
  input,
}: {
  id: string;
  input: {
    completedSteps?: string[];
  };
}) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }

  const client = generateClient();

  try {
    // Validate required parameters
    if (!id) {
      throw new Error("Application id is required");
    }

    if (Object.keys(input).length === 0) {
      throw new Error("At least one field to update is required");
    }

    const response = await client.graphql({
      query: `
        mutation UpdateApplication($input: UpdateApplicationInput!) {
          updateApplication(input: $input) {
            id
          }
        }
      `,
      variables: {
        input: {
          id,
          ...input,
        },
      },
      authMode: "userPool",
    });

    if ("data" in response) {
      return response.data.updateApplication;
    }

    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error updating Application:", error);
    throw error;
  }
};

export const getApplicationAssociations = async ({
  applicationId,
  associationType,
}: {
  applicationId: string;
  associationType:
    | "Award"
    | "Education"
    | "SpecializedExperience"
    | "PastJob"
    | "Volunteer"
    | "Resume";
}) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }

  const client = generateClient();

  try {
    // Validate required parameters
    if (!applicationId) {
      throw new Error("applicationId is required");
    }

    // Build the query name based on the associationType
    const queryName = `list${associationType}Applications`;

    // Build the filter to match the applicationId
    const filter = {
      applicationId: { eq: applicationId },
    };

    // Define the fields to fetch based on the associationType
    const getSpecificFields = () => {
      switch (associationType) {
        case "Award":
          return `
            title
            date
            userId
          `;
        case "Education":
          return `
            degree
            major
            school
            date
            title
            gpa
            userConfirmed
            userId
          `;
        case "SpecializedExperience":
          return `
            title
            description
            userConfirmed
            paragraph
            initialMessage
            userId
          `;
        case "PastJob":
          return `
            title
            organization
            startDate
            endDate
            hours
            gsLevel
            responsibilities
            userId
          `;
        case "Volunteer":
          return `
            title
            organization
            startDate
            endDate
            hours
            gsLevel
            responsibilities
            userId
          `;
        case "Resume":
          return `
            fileName
            userId
          `;
        default:
          return "";
      }
    };

    // Execute the query to get the junction table entries
    const junctionResponse = await client.graphql({
      query: `
        query List${associationType}Applications($filter: Model${associationType}ApplicationFilterInput) {
          ${queryName}(filter: $filter) {
            items {
              id
              applicationId
              ${
                associationType.charAt(0).toLowerCase() +
                associationType.slice(1)
              }Id
              ${
                associationType.charAt(0).toLowerCase() +
                associationType.slice(1)
              } {
                id
                ${getSpecificFields()}
                createdAt
                updatedAt
              }
              createdAt
              updatedAt
            }
          }
        }
      `,
      variables: { filter },
      authMode: "userPool",
    });

    if ("data" in junctionResponse) {
      // Extract and return just the associated items, not the junction records
      const junctionItems = junctionResponse.data[queryName].items;
      const associatedItems = junctionItems
        .map(
          (item: any) =>
            item[
              associationType.charAt(0).toLowerCase() + associationType.slice(1)
            ]
        )
        .filter(Boolean); // Filter out any null items

      return associatedItems;
    }

    throw new Error(
      `Unexpected response format from GraphQL operation for ${associationType}`
    );
  } catch (error) {
    console.error(
      `Error fetching ${associationType} associations for Application:`,
      error
    );
    throw error;
  }
};

export const listApplications = async () => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }

  const client = generateClient();
  try {
    const response = await client.graphql({
      query: `
        query ListApplications {
          listApplications {
            items {
              id
              jobId
              userId
              createdAt
              updatedAt
            }
          }
        }
      `,
      authMode: "userPool",
    });

    if ("data" in response) {
      return response.data.listApplications.items;
    }
    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error fetching Applications:", error);
    throw error;
  }
};

export const listUserApplications = async ({ userId }: { userId: string }) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }

  const client = generateClient();
  try {
    // Validate required parameter
    if (!userId) {
      throw new Error("userId is required");
    }

    const response = await client.graphql({
      query: `
        query ListApplications($filter: ModelApplicationFilterInput) {
          listApplications(filter: $filter) {
            items {
              id
              jobId
              userId
              job {
                id
                title
                department
                agencyDescription
              }
              createdAt
              updatedAt
            }
          }
        }
      `,
      variables: {
        filter: {
          userId: { eq: userId },
        },
      },
      authMode: "userPool",
    });

    if ("data" in response) {
      return response.data.listApplications.items;
    }
    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error fetching user Applications:", error);
    throw error;
  }
};
