import { generateClient } from "aws-amplify/api";
import { fetchAuthSession } from "aws-amplify/auth";
export const listUserResumes = async () => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }

  const client = generateClient();
  try {
    const response = await client.graphql({
      query: `
        query ListUserResumes {
          listUserResumes {
            items {
              id
              jobId
              userId
              createdAt
              updatedAt
            }
          }
        }
      `,
      authMode: "userPool",
    });

    if ("data" in response) {
      return response.data.listUserResumes.items;
    }
    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error fetching UserResumes:", error);
    throw error;
  }
};

export const createAndSaveUserResume = async ({
  jobId,
  userId,
}: {
  jobId: string;
  userId: string;
}) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    // Redirect to login page
    return;
  }
  const client = generateClient();
  try {
    // Validate required parameters
    if (!jobId || !userId) {
      throw new Error("jobId and userId are required parameters");
    }

    // Create the UserResume input object
    const userResumeInput = {
      jobId,
      userId,
      // Note: The ID will be auto-generated by Amplify
    };

    // Use the client.models approach in Amplify v2
    const response = await client.graphql({
      query: `
        mutation CreateUserResume($input: CreateUserResumeInput!) {
          createUserResume(input: $input) {
            id
            jobId
            userId
            createdAt
            updatedAt
          }
        }
      `,
      variables: {
        input: userResumeInput,
      },
      authMode: "userPool",
    });

    // Return the created UserResume
    if ("data" in response) {
      return response.data.createUserResume;
    }
    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error creating UserResume:", error);
    throw error;
  }
};

export const getUserResumeWithJob = async ({ id }: { id: string }) => {
  try {
    const session = await fetchAuthSession();
    if (!session.tokens) {
      throw new Error("No valid authentication session found");
    }
  } catch (error) {
    console.error("No user is signed in");
    return;
  }
  const client = generateClient();
  try {
    const response = await client.graphql({
      query: `
      query GetUserResume($id: ID!) {
        getUserResume(id: $id) {
        id
        jobId
        userId
        job {
          id
            title
            department
            agencyDescription
            duties
            evaluationCriteria
            qualificationsSummary
            requiredDocuments
            usaJobsId
        }
        createdAt
        updatedAt
        }
      }
      `,
      variables: { id },
      authMode: "userPool",
    });

    if ("data" in response) {
      return response.data.getUserResume;
    }
    throw new Error("Unexpected response format from GraphQL operation");
  } catch (error) {
    console.error("Error fetching UserResume:", error);
    throw error;
  }
};
